name: basic-docker

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ v4
    - uses: actions/setup-node@ v4
      with:
        node-version: '18'

    - name: Install NNewman
      run: npm install -g new m an \
        new m an-reporter-htm lextra

    - name: Run API tests
      run: new m an run postm an/collection.json \
        -e postm an/environm ent.dev.json