name: basic-docker

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: hello
    steps: 
      - name: saludadno
        run: echo "hola a la clase"
  despachando:
      runs-on: ubuntu-latest
      name: bye
      needs: hello
      steps: 
        - name: despidiendo
          run: echo "bye bye a la clase"
